### ISSUE TITLE
Why GPLv2?

### ISSUE THREAD

**Issue by liam-middlebrook** [fortnight/Grammar_Game#1]
Why not use the GPLv3+? Is there anything in the GPLv3 that would give you a reason not to use it over the v2?

**Comment by fortnight** [comment]
You bring up a good point. In truth, I was in a rush when creating the repository, and GPL v2 was the first license in the drop-down menu.

**Comment by Nolski** [comment]
This might be helpful if you're thinking of changing licenses.
https://www.gnu.org/licenses/gpl-faq.html#gpl-compat-matrix

**Comment by fortnight** [comment]
Thanks for the resource Nolski! I hadn't done any code yet, so changing the license wasn't a problem
